### ISSUE TITLE
broken on 2.9.11 prerelease

### ISSUE THREAD

**Issue by sdip15fa** [andrejilderda/joplin-macos-native-theme#83]
Hi there, after upgrading to 2.9.11 prerelease macos theme is now broken and would cause the joplin desktop app unable to render.
(tested on 2.9.11 prerelease AND latest dev branch)
![Screenshot_20221028_213122-1](https://user-images.githubusercontent.com/91375035/198637693-f245e1dd-ccd8-4488-81e9-8a2a64a80c55.png)

**Comment by ScriptInfra** [comment]
Which OS are you on? I was able to get Joplin version 2.9.11 working on macOS with the theme applied. You could also try reinstalling the theme if you haven't already.

**Comment by sdip15fa** [comment]
> Which OS are you on? I was able to get Joplin version 2.9.11 working on macOS with the theme applied. You could also try reinstalling the theme if you haven't already.

arch linux

**Comment by sdip15fa** [comment]
would you happen to know where the plugin settings are stored?

**Comment by ScriptInfra** [comment]
> would you happen to know where the plugin settings are stored?

I'm afraid not. The only directories I am aware of that are related to plugins is /Users/username/.config./joplin-desktop/plugins and /Users/username/.config./joplin-desktop/cache

**Comment by sdip15fa** [comment]
Thanks @ScriptInfra, I have resolved it by deleting all macos theme entries in the settings table of database.sqlite.

**Comment by andrejilderda** [comment]
Good to hear things have been solved. Thanks for thinking along @ScriptInfra !

**Comment by mikicvi** [comment]
Hey, I'm having the same issue with the theme ever since 2.9.11, and it's the same for 2.9.12. 
I've tried the fix mentioned above, but its still the same.

Any other suggestions?

**Comment by sdip15fa** [comment]
> Hey, I'm having the same issue with the theme ever since 2.9.11, and it's the same for 2.9.12. 
> 
> I've tried the fix mentioned above, but its still the same.
> 
> 
> 
> Any other suggestions?

Same here, so I am still using 2.9.8.
But I have noticed disabling all other plugins it does work.

**Comment by mikicvi** [comment]
> > Hey, I'm having the same issue with the theme ever since 2.9.11, and it's the same for 2.9.12.
> > I've tried the fix mentioned above, but its still the same.
> > Any other suggestions?
> 
> Same here, so I am still using 2.9.8. But I have noticed disabling all other plugins it does work.

Unfortunately, that is the only plugin I use, since I suspected that other plugins were causing the issue, so I got rid of them since I never really used them anyway...
I also tried various different built in themes, but to no avail, which is too bad, since this is my favourite theme for Joplin.

**Comment by sdip15fa** [comment]
> > > Hey, I'm having the same issue with the theme ever since 2.9.11, and it's the same for 2.9.12.
> 
> > > I've tried the fix mentioned above, but its still the same.
> 
> > > Any other suggestions?
> 
> > 
> 
> > Same here, so I am still using 2.9.8. But I have noticed disabling all other plugins it does work.
> 
> 
> 
> Unfortunately, that is the only plugin I use, since I suspected that other plugins were causing the issue, so I got rid of them since I never really used them anyway...
> 
> I also tried various different built in themes, but to no avail, which is too bad, since this is my favourite theme for Joplin. 
> 
> 
> 
> 

Did you try a clean install? That is removing everything in ~/.config/joplin-desktop/plugins

**Comment by sdip15fa** [comment]
or just test using different HOME variable, i.e. 
HOME=~/Downloads joplin-desktop

**Comment by sdip15fa** [comment]
It did work for me if it’s a clean install. Did you get any errors (I got none).

**Comment by mikicvi** [comment]
Tried wiping the .config directory. I restarted Joplin couple of times and so far so good.., I can report more during Sunday when I get more time. 

Just a quick question - do you get this weird theme changing behaviour upon launching Joplin? It feels as if it goes back to default theme every time, and then the plugin theme is applied(happens within 1 sec window)...

**Comment by sdip15fa** [comment]
> Tried wiping the .config directory. I restarted Joplin couple of times and so far so good.., I can report more during Sunday when I get more time.
> 
> Just a quick question - do you get this weird theme changing behaviour upon launching Joplin? It feels as if it goes back to default theme every time, and then the plugin theme is applied(happens within 1 sec window)...

yeah, this happens to me when it works

**Comment by mikicvi** [comment]
> > Tried wiping the .config directory. I restarted Joplin couple of times and so far so good.., I can report more during Sunday when I get more time.
> > Just a quick question - do you get this weird theme changing behaviour upon launching Joplin? It feels as if it goes back to default theme every time, and then the plugin theme is applied(happens within 1 sec window)...
> 
> yeah, this happens to me when it works

Just FYI that only started happening with 2.9.11 and persists through 2.9.12, at least in my case.

**Comment by sdip15fa** [comment]
> > > Tried wiping the .config directory. I restarted Joplin couple of times and so far so good.., I can report more during Sunday when I get more time.
> > > Just a quick question - do you get this weird theme changing behaviour upon launching Joplin? It feels as if it goes back to default theme every time, and then the plugin theme is applied(happens within 1 sec window)...
> > 
> > 
> > yeah, this happens to me when it works
> 
> Just FYI that only started happening with 2.9.11 and persists through 2.9.12, at least in my case.

same here

**Comment by andrejilderda** [comment]
Hmmm... thanks everyone for testing and looking into this. For me everything is working fine on 2.9.12 and I can't reproduce the issue. Maybe because I updated from an older stable version directly to 2.9.12? 

That being said, is anyone still experiencing problems?

Btw. I've also just commented here: https://github.com/laurent22/joplin/issues/7051#issuecomment-1304808586

**Comment by sdip15fa** [comment]
![Screenshot_20221107_205439](https://user-images.githubusercontent.com/91375035/200315586-96386892-47a2-4cfd-9b16-126b286e5c0a.png)

I think just installing these will do. And I can't locate which plugin is the problem after a lot of testing

**Comment by sdip15fa** [comment]
![Screenshot_20221107_211022](https://user-images.githubusercontent.com/91375035/200318538-d6229ce5-48f9-4153-96b0-1fbf004d5471.png)
Nothing there!

**Comment by andrejilderda** [comment]
Hmm... so, just to be sure, everything works fine when the theme is uninstalled/disabled? I can't see how the theme is able to cause your issues, since I'm not doing anything too exciting technically. 😅

**Comment by sdip15fa** [comment]
> 



> Hmm... so, just to be sure, everything works fine when the theme is uninstalled/disabled? I can't see how the theme is able to cause your issues, since I'm not doing anything too exciting technically. sweat_smile

Yup, works as soon as I uninstall it (on my setup). On a fresh install it really is not broken.

**Comment by sdip15fa** [comment]
Oh, forgot to tell one of the plugins (enhancement) is my own fork

**Comment by sdip15fa** [comment]
And you are right, still not broken after installing those... emm...

**Comment by sdip15fa** [comment]
![Screenshot_20221107_212828](https://user-images.githubusercontent.com/91375035/200322347-2813e13e-87a3-4c1e-82d2-f7737ca8620f.png)
Here, just tested, certainly broken after installing all of these!

**Comment by sdip15fa** [comment]
Ok, after some testing, it seems like with a same plugins set:
- a fresh install would work
- my install doesn't
So it might be that some settings went wrong.

**Comment by sdip15fa** [comment]
Seems like it isn't so simple. After some configuration (sync target) it is broken again...

**Comment by sdip15fa** [comment]
So I ended up resolving the issue by removing a lot of plugins that didn't work with macos theme
