### ISSUE TITLE
Plugin freezes Joplin (has workaround)

### ISSUE THREAD

**Issue by benmordecai** [andrejilderda/joplin-macos-native-theme#96]
With v1.3.11, I cannot enable the plugin in Windows 11 or Arch Linux versions of Joplin or it will completely freezes joplin such that it is completely unresponsive to input. The menus will not even open.

**Comment by jibedoubleve** [comment]
The problem is still there with Joplin 2.10.6 (prod, darwin) without any plugins

I tested on

* Windows 10 (10.0.19045) 
* macOS Ventura 13.0.1
* Different notebooks configurations

It seems that UI freezes when I expand group of notebooks with emojis

Related issue #88

**Comment by benmordecai** [comment]
I  can expand groups of notebooks with emojis but only when the MacOS plugin is disabled

**Comment by dsouzadrian** [comment]
Confirmed the same behavior others are seeing. Cleared emoji's from all notebooks and was able to use the Mac OS Theme without issue. If I assign emoji's to any notebook - Joplin loads only a blank screen [1]

The only way to get it back is to go the config directory plugin's and delete the .jpl file.

[1]

![image](https://user-images.githubusercontent.com/8682704/236276277-0106ba64-4678-452f-b7cd-3b2ef485dd58.png)

**Comment by pelijaro** [comment]
> Confirmed the same behavior others are seeing. Cleared emoji's from all notebooks and was able to use the Mac OS Theme without issue. If I assign emoji's to any notebook - Joplin loads only a blank screen [1]
> 
> The only way to get it back is to go the config directory plugin's and delete the .jpl file.
> 
> [1]
> 
> ![image](https://user-images.githubusercontent.com/8682704/236276277-0106ba64-4678-452f-b7cd-3b2ef485dd58.png)

Same error over here, I have disabled the plugin and joplin works fine, I see it's a problem with the emojis, I could remove them but it helps me to quickly identify what's what.

Let's see if the developer can fix it soon!

**Comment by Aman-Anas** [comment]
It seems that setting the emojis via the "Choose emoji..." dialog triggers this issue, but adding the emojis into the text box does not.

no problem:
![image](https://github.com/andrejilderda/joplin-macos-native-theme/assets/41600372/4e422811-641c-49b5-a5a2-60b4abc53c0d)


problem next time on startup:
![image](https://github.com/andrejilderda/joplin-macos-native-theme/assets/41600372/cff68da7-a444-43ac-9ec8-fe0d4b76ff63)

Hope it gets fixed soon! :)

**Comment by ScriptInfra** [comment]
Maybe this is fixed in v2.11.7?

Improved: Add support for AVIF image format ([#8175](https://github.com/laurent22/joplin/issues/8175))
Improved: Improved word count when em-dash is used ([#8083](https://github.com/laurent22/joplin/issues/8083))
Improved: Updated packages aws, buildTools
Fixed: "New note" buttons so large they occlude Search ([#8249](https://github.com/laurent22/joplin/pull/8249)) ([#8159](https://github.com/laurent22/joplin/issues/8159) by Rio Sinnott)
**Fixed: Window is white on startup ([#7484](https://github.com/laurent22/joplin/issues/7484))**

**Comment by pelijaro** [comment]
> Maybe this is fixed in v2.11.7?
> 
> Improved: Add support for AVIF image format ([#8175](https://github.com/laurent22/joplin/issues/8175)) Improved: Improved word count when em-dash is used ([#8083](https://github.com/laurent22/joplin/issues/8083)) Improved: Updated packages aws, buildTools Fixed: "New note" buttons so large they occlude Search ([#8249](https://github.com/laurent22/joplin/pull/8249)) ([#8159](https://github.com/laurent22/joplin/issues/8159) by Rio Sinnott) **Fixed: Window is white on startup ([#7484](https://github.com/laurent22/joplin/issues/7484))**

Version 2.11.11 has been released and the bug is still occurring, I was hopeful :(

**Comment by benmordecai** [comment]
I can confirm that @Aman-Anas solution works and I manually changed over all my notes to use emojis in the title rather than setting an emoji from Joplin's picker.

**Comment by andypiper** [comment]
Definitely works if you do switch from using emoji icons for the notebooks (folders), to including the emoji in the title instead... *but* this then breaks the alphabetical sort of the notebooks, which makes it much more annoying to use, even if the theme looks a bit nicer. Frustrating.

**Comment by d1sc0v3r** [comment]
Unfortunately, the issue persists as of version 3.0.14. This renders the theme unusable on your typical corp windows device with the current version.

**Comment by benmordecai** [comment]
@d1sc0v3r - do you have emoji's set through the New Notebook dialog? If so, there is a workaround above.

**Comment by CodingPupper3033** [comment]
You know, I am starting to think that is the CSS for all list item rows, not just the emoji ones, which probably is not narrowing down the issue much

**Comment by CodingPupper3033** [comment]
Hey, sorry for the late reply.

I have Node and npm installed as I am running the debugging method. I am alright with front-end, but nowhere near an expert.

For me, it was the whole section. Unfortunately, I am at a loss for how to proceed.

Additionally, I am unsure how other users are running the application, but I am using the Linux AppImage version on Ubuntu 25.04.

If you have any suggestions, or knowledge of what other "subclasses" (does CSS even have subclasses) rely on it, or where icons are rendered, let me know and I can play around with it! I don't have enough experience with Joplin plugins, nor your plugin in particular.

**Comment by CodingPupper3033** [comment]
Hello again,

I have found a method to reproduce the issue. 
1. Create three notebooks, each with an emoji, nested to create a "parent notebook" "child notebook" and "grandchild notebook".  
2. Close/minimize just the parent notebook. 
3. Close the application
4. Open the application
5. Attempt to unminimize the parent notebook
6. The application freezes

I got this to happen on two linux devices, each installed using the Joplin-provided command: `https://nextcloud.codingpupper3033.com/remote.php/dav/files/CodingPupper3033/Documents/Joplin/`
And I ran `~/.joplin/Joplin.AppImage --no-sandbox` to start it, installed the plugin, clicked restart, then ran the command again to finish the restart

**Comment by hyuri** [comment]
I've just solved the problem on my end, by deleting this one line:
```css
line-height: 2.8rem;
```

In `~/.config/joplin-desktop/cache/com.andrejilderda.macOSTheme/dist/macos-theme-for-joplin.css`
For good measure, I also edited the corresponding line in `~/.config/joplin-desktop/cache/com.andrejilderda.macOSTheme/scss/components/_components.sidebar.scss`

Not only did it solve the freezing/crashing on scrolling the sidebar up/down, but it also solved another issue that had been bugging me for a long time: Clicking on a note title to edit it now works. Before this fix, I had to click a few pixels above the title to be able to edit it.

The problem is that it's in the cache folder, so it's not going to persist for very long.

@andrejilderda Can you confirm and issue an update, when possible, please?

@CodingPupper3033 Thanks for the pointers.
